name: Deploy EC2 Instance

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: eu-central-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Intall boto3
        run: pip install boto3

      - name: Print Secrets
        run: echo AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY

      - name: Deploy EC2 instance
        run: python3 deploy.py AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
